### ISSUE TITLE
sendErrorMessage use wrong field to create notification

### ISSUE THREAD

**Issue by phulamnguyen** [pkp/plagiarism#58]
function createTrivialNotification($userId, ...) { .. } has the first params is $userId. But in the function sendErrorMessage, it uses table userGroup and passes group id to the param userId of function createTrivialNotification. So when sendErrorMessage is called, it makes an error insert notification because of foreign key constraints.
Please fix it soon.

**Comment by touhidurabir** [comment]
@phulamnguyen which version of plugin are you using ? and also for which version of OJS/OMP ? I can see that in the current latest release at https://github.com/pkp/plagiarism/releases , it has been fixed .

**Comment by touhidurabir** [comment]
We haven't released any version for 3.4.0+ yet . I understand where the problem is arising .  Currently we are working to update the ithenticate api (see pkp/plagiarism#52) to the latest version and once that is done, we will release for 3.4.0+ . in the mean time if you need to use it with 3.4.0+, you need to checkout from the latest `main` branch to make it work.

**Comment by touhidurabir** [comment]
Not planned yet . see https://github.com/pkp/plagiarism/issues/58#issuecomment-1975795049
